core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Third Party Allauth
    # path('accounts/', include('allauth.urls')),

    # Post App
    path('', include('post.urls', namespace='post')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("category/<slug:slug>/<int:pk>/", views.CategoryListView.as_view(), name="category_list"),
    path("article/<slug:slug>/<int:pk>/", views.PostDetailView.as_view(), name="post_detail"), # post detail
    path('search/', views.SearchView.as_view(), name="search"), # Search
    path('comment/<slug:slug>/<int:pk>/', views.comment_add, name="comment"), # comment
    path('aboutus/', views.aboutus, name="aboutus"), # comment


    # path("article/add_post", views.post_add, name="add_post"),
    # path("article/edit/<int:id>", views.post_update, name="update_post"),
    # path('article/delete/<int:id>',views.post_delete, name='delete_post'),
    # # Category
    # path("category/all_categories", views.all_category, name="all_categories"),    
    # path("category/add_category", views.add_category, name="add_category"),    
    # path("category/list/<slug:slug>", views.category_post_list, name="category_post_list"),
    # # Like
    # path('article/like/<int:id>', views.post_like, name='like_post'),
    # # Comment
    # path('article/comment/<int:id>', views.post_comment, name='post_comment'),
    # path('article/comment/answer/<int:id>/<int:post_id>', views.comment_answer, name='comment_answer' )

]

templates/partials/_footer.html
{% load static %}   



<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="widget">
                    <div class="footer-text text-center">
                        <a href="index.html"><img src="images/version/garden-footer-logo.png" alt="" class="img-fluid"></a>
                        <p>Forest Time is a personal blog for handcrafted, cameramade photography content, fashion styles from independent creatives around the world.</p>
                        <div class="social">
                            <a href="{{ site_config.facebook }}" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-facebook"></i></a>              
                            <a href="{{ site_config.twitter }}" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i class="fa fa-twitter"></i></a>
                            <a href="{{ site_config.instagram }}" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i class="fa fa-instagram"></i></a>
                            {% comment %} <a href="{{ site_config.facebook }}" data-toggle="tooltip" data-placement="bottom" title="Google Plus"><i class="fa fa-google-plus"></i></a>
                            <a href="{{ site_config.facebook }}" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i class="fa fa-pinterest"></i></a> {% endcomment %}
                        </div>

                        <hr class="invis">

                        <div class="newsletter-widget text-center">
                            <form class="form-inline">
                                <input type="text" class="form-control" placeholder="Enter your email address">
                                <button type="submit" class="btn btn-primary">Subscribe <i class="fa fa-envelope-open-o"></i></button>
                            </form>
                        </div><!-- end newsletter -->
                    </div><!-- end footer-text -->
                </div><!-- end widget -->
            </div><!-- end col -->
        </div>

        <div class="row">
            <div class="col-md-12 text-center">
                <br>
                <br>
                <div class="copyright">&copy; Forest Time. Design: <a href="http://html.design">HTML Design</a>.</div>
            </div>
        </div>
    </div><!-- end container -->
</footer><!-- end footer -->

{% comment %} <div class="dmtop">Scroll to Top</div> {% endcomment %}

templates/partials/_head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Site Metas -->
    <title>Forest Time - Stylish Magazine Blog Template</title>
    <meta name="keywords" content="{{site_config.keywords}}">
    <meta name="description" content="{{site_config.description}}">
    <meta name="author" content="Tunahan Çelebi">
    
    <!-- Site Icons -->
    <link rel="shortcut icon" href="{{site_config.logo.url}}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{{site_config.logo.url}}">
    <link rel="icon" type="image/x-icon" href="{{site_config.logo.url}}">
    
    <!-- Design fonts -->
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet"> 

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- FontAwesome Icons core CSS -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'style.css' %}" rel="stylesheet">

    <!-- Responsive styles for this template -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

    <!-- Colors for this template -->
    <link href="{% static 'css/colors.css' %}" rel="stylesheet">

    <!-- Version Garden CSS for this template -->
    <link href="{% static 'css/version/garden.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

templates/partials/_messages.html
{% load static %}

{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
 {% endif %}

templates/partials/_navbar.html
{% load static %}


<div class="collapse top-search" id="collapseExample">
    <div class="card card-block">
        <div class="newsletter-widget text-center">
            <form method='GET' class="form-inline" action='{% url "post:search" %}'>
                {% csrf_token %}
                <input type="text" class="form-control" name='search_value' placeholder="What you are looking for?">
                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
            </form>
        </div><!-- end newsletter -->
    </div>
</div><!-- end top-search -->

<div class="topbar-section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-6 hidden-xs-down">
                <div class="topsocial">
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i
                            class="fa fa-facebook"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Youtube"><i
                            class="fa fa-youtube"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Pinterest"><i
                            class="fa fa-pinterest"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Twitter"><i
                            class="fa fa-twitter"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Flickr"><i
                            class="fa fa-flickr"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Instagram"><i
                            class="fa fa-instagram"></i></a>
                    <a href="#" data-toggle="tooltip" data-placement="bottom" title="Google+"><i
                            class="fa fa-google-plus"></i></a>
                </div><!-- end social -->
            </div><!-- end col -->

            <div class="col-lg-4 hidden-md-down">
            </div><!-- end col -->

            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                <div class="topsearch text-right">
                    <a data-toggle="collapse" href="#collapseExample" aria-expanded="false"
                        aria-controls="collapseExample"><i class="fa fa-search"></i> Search</a>
                </div><!-- end search -->
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end header-logo -->
</div><!-- end topbar -->

<div class="header-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="logo">
                    <a href="{% url 'post:home' %}"><img src="{{site_config.logo.url}}" alt="Resim Bulunamadı"></a>
                </div><!-- end logo -->
            </div>
        </div><!-- end row -->
    </div><!-- end header-logo -->
</div><!-- end header -->

<header class="header">
    <div class="container">
        <nav class="navbar navbar-inverse navbar-toggleable-md">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Forest Timemenu"
                aria-controls="Forest Timemenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-md-center" id="Forest Timemenu">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link color-green-hover" href="{% url 'post:home' %}">Home</a>
                    </li>
                    {% for category in categories %}
                    <li class="nav-item">
                        <a class="nav-link color-green-hover" href="{% url 'post:category_list' category.slug category.id %}">{{category.name}}</a>
                    </li>
                    {% endfor %}
                    <li class="nav-item">
                        <a class="nav-link color-green-hover" href="{% url 'post:aboutus' %}">Sohbet Edelim</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div><!-- end container -->
</header><!-- end header -->

templates/partials/base.html
{% load static %}

{% include 'partials/_head.html' %}

<body>
    <div id="wrapper">
        {% include 'partials/_navbar.html' %}

        {% block content %}
        
        {% endblock content %}
        
        
        {% include 'partials/_footer.html' %}
    </div><!-- end wrapper -->


    

    <!-- Core JavaScript ================================================== -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/tether.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

</body>

</html>